Add offset reset strategy param
FoxComm/metamorphosis pull request #1
Opened 2016-12-12 14:54 UTC by tonypizzicato

2016-12-14 09:12 UTC, jmataya requested changes
This is a good capability to add. I just have one request around validating the contents of the offset parameter.

Also, can you update the instructions in the README about the removal of the `partition` parameter?

2016-12-14 09:12 UTC, jmataya commented on consumer.go
> +	consumerConfig.AutoOffsetReset = offsetStrategy
Can you add some validation to make sure that we're enforcing that `offsetStrategy` is either `OffsetResetSmallest` or `OffsetResetLargest`?

2016-12-15 16:40 UTC, tonypizzicato commented on consumer.go
> +	consumerConfig.AutoOffsetReset = offsetStrategy
@jmataya done

2016-12-15 16:42 UTC, tonypizzicato commented
what do you mean by `update the instructions in the README about the removal of the partition parameter`? it has no info about this parameter :)

2016-12-16 18:30 UTC, jmataya commented
@tonypizzicato Nevermind, I see the change in the README. This looks great!

2016-12-16 18:30 UTC, jmataya approved these changes

2016-12-16 18:30 UTC, merged